using System.Text;
using Graphify.Graph;

namespace Graphify.Export;

/// <summary>
/// Exports knowledge graph as an Obsidian vault with one .md file per node.
/// Uses [[wikilinks]] for edges to create an interconnected knowledge base.
/// </summary>
public sealed class ObsidianExporter : IGraphExporter
{
    public string Format => "obsidian";

    /// <summary>
    /// Export graph to Obsidian vault format. outputPath should be a directory.
    /// </summary>
    public async Task ExportAsync(KnowledgeGraph graph, string outputPath, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(graph);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);

        var outputDir = new DirectoryInfo(outputPath);
        outputDir.Create();

        var nodes = graph.GetNodes().ToList();

        // Generate community labels
        var communities = nodes
            .Where(n => n.Community.HasValue)
            .GroupBy(n => n.Community!.Value)
            .ToDictionary(g => g.Key, g => $"Community {g.Key}");

        // Create one markdown file per node
        foreach (var node in nodes)
        {
            var content = GenerateNodeFile(graph, node, communities);
            var filename = SafeFilename(node.Label ?? node.Id) + ".md";
            var filePath = Path.Combine(outputDir.FullName, filename);
            
            await File.WriteAllTextAsync(filePath, content, cancellationToken);
        }

        // Create index file
        var indexContent = GenerateIndexFile(graph, nodes, communities);
        await File.WriteAllTextAsync(Path.Combine(outputDir.FullName, "_Index.md"), indexContent, cancellationToken);
    }

    private static string GenerateNodeFile(
        KnowledgeGraph graph, 
        Models.GraphNode node,
        Dictionary<int, string> communities)
    {
        var sb = new StringBuilder();
        var nodeLabel = node.Label ?? node.Id;

        // YAML frontmatter
        sb.AppendLine("---");
        sb.AppendLine($"id: {node.Id}");
        sb.AppendLine($"type: {node.Type}");
        
        if (node.Community.HasValue && communities.TryGetValue(node.Community.Value, out var communityLabel))
        {
            sb.AppendLine($"community: \"{communityLabel}\"");
        }

        if (node.Metadata != null)
        {
            foreach (var (key, value) in node.Metadata.OrderBy(kvp => kvp.Key))
            {
                if (key != "label" && !string.IsNullOrWhiteSpace(value))
                {
                    sb.AppendLine($"{key}: \"{EscapeYaml(value)}\"");
                }
            }
        }

        var degree = graph.GetDegree(node.Id);
        sb.AppendLine($"connections: {degree}");
        sb.AppendLine("---");
        sb.AppendLine();

        // Main content
        sb.AppendLine($"# {nodeLabel}");
        sb.AppendLine();

        // Metadata section
        sb.AppendLine("## Properties");
        sb.AppendLine();
        sb.AppendLine($"- **Type:** {node.Type}");
        sb.AppendLine($"- **ID:** `{node.Id}`");
        sb.AppendLine($"- **Connections:** {degree}");
        
        if (node.Community.HasValue && communities.TryGetValue(node.Community.Value, out var comm))
        {
            sb.AppendLine($"- **Community:** {comm}");
        }

        if (node.Metadata != null && node.Metadata.TryGetValue("source_file", out var sourceFile))
        {
            sb.AppendLine($"- **Source:** `{sourceFile}`");
        }

        sb.AppendLine();

        // Connections grouped by relationship
        var connections = GetConnectionsByRelationship(graph, node);

        if (connections.Count > 0)
        {
            sb.AppendLine("## Connections");
            sb.AppendLine();

            foreach (var (relationship, linkedNodes) in connections.OrderByDescending(kvp => kvp.Value.Count))
            {
                sb.AppendLine($"### {relationship}");
                sb.AppendLine();

                foreach (var (linkedNode, confidence) in linkedNodes.OrderBy(x => x.LinkedNode.Label ?? x.LinkedNode.Id))
                {
                    var linkedLabel = linkedNode.Label ?? linkedNode.Id;
                    var confTag = confidence != Models.Confidence.Extracted ? $" `{confidence}`" : "";
                    sb.AppendLine($"- [[{linkedLabel}]]{confTag}");
                }

                sb.AppendLine();
            }
        }
        else
        {
            sb.AppendLine("## Connections");
            sb.AppendLine();
            sb.AppendLine("*No connections found*");
            sb.AppendLine();
        }

        // Backlinks section (for context)
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*Generated by graphify. Part of the knowledge graph vault.*");

        return sb.ToString();
    }

    private static string GenerateIndexFile(
        KnowledgeGraph graph,
        List<Models.GraphNode> nodes,
        Dictionary<int, string> communities)
    {
        var sb = new StringBuilder();

        sb.AppendLine("---");
        sb.AppendLine("title: Knowledge Graph Index");
        sb.AppendLine($"generated: {DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("---");
        sb.AppendLine();

        sb.AppendLine("# Knowledge Graph Index");
        sb.AppendLine();
        sb.AppendLine("> Central hub for navigating the knowledge graph in Obsidian");
        sb.AppendLine();

        sb.AppendLine("## Statistics");
        sb.AppendLine();
        sb.AppendLine($"- **Nodes:** {nodes.Count}");
        sb.AppendLine($"- **Edges:** {graph.EdgeCount}");
        sb.AppendLine($"- **Communities:** {communities.Count}");
        sb.AppendLine();

        // Top nodes by degree
        var topNodes = graph.GetHighestDegreeNodes(20).ToList();
        if (topNodes.Count > 0)
        {
            sb.AppendLine("## Most Connected Nodes");
            sb.AppendLine();

            foreach (var (node, degree) in topNodes)
            {
                var label = node.Label ?? node.Id;
                sb.AppendLine($"- [[{label}]] ({degree} connections)");
            }
            sb.AppendLine();
        }

        // Nodes by community
        if (communities.Count > 0)
        {
            sb.AppendLine("## By Community");
            sb.AppendLine();

            var nodesByCommunity = nodes
                .Where(n => n.Community.HasValue)
                .GroupBy(n => n.Community!.Value)
                .OrderByDescending(g => g.Count());

            foreach (var community in nodesByCommunity)
            {
                var communityLabel = communities[community.Key];
                sb.AppendLine($"### {communityLabel}");
                sb.AppendLine();
                sb.AppendLine($"*{community.Count()} nodes*");
                sb.AppendLine();

                foreach (var node in community.OrderByDescending(n => graph.GetDegree(n.Id)).Take(10))
                {
                    var label = node.Label ?? node.Id;
                    sb.AppendLine($"- [[{label}]]");
                }

                if (community.Count() > 10)
                {
                    sb.AppendLine($"- *... and {community.Count() - 10} more*");
                }
                sb.AppendLine();
            }
        }

        // Node types
        var nodesByType = nodes
            .GroupBy(n => n.Type)
            .OrderByDescending(g => g.Count())
            .ToList();

        if (nodesByType.Count > 0)
        {
            sb.AppendLine("## By Type");
            sb.AppendLine();

            foreach (var typeGroup in nodesByType)
            {
                sb.AppendLine($"### {typeGroup.Key}");
                sb.AppendLine($"*{typeGroup.Count()} nodes*");
                sb.AppendLine();
            }
        }

        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*Generated by [graphify](https://github.com/safishamsi/graphify)*");

        return sb.ToString();
    }

    private static Dictionary<string, List<(Models.GraphNode LinkedNode, Models.Confidence Confidence)>> GetConnectionsByRelationship(
        KnowledgeGraph graph,
        Models.GraphNode node)
    {
        var result = new Dictionary<string, List<(Models.GraphNode, Models.Confidence)>>();

        // Get all edges connected to this node
        var edges = graph.GetEdges(node.Id);

        foreach (var edge in edges)
        {
            var relationship = edge.Relationship ?? "related_to";
            var linkedNode = edge.Source.Id == node.Id ? edge.Target : edge.Source;

            if (!result.ContainsKey(relationship))
            {
                result[relationship] = new List<(Models.GraphNode, Models.Confidence)>();
            }

            // Avoid duplicates
            if (!result[relationship].Any(x => x.Item1.Id == linkedNode.Id))
            {
                result[relationship].Add((linkedNode, edge.Confidence));
            }
        }

        return result;
    }

    private static string SafeFilename(string name)
    {
        var safe = name;
        
        // Obsidian supports most characters, but avoid some problematic ones
        foreach (var c in Path.GetInvalidFileNameChars())
        {
            safe = safe.Replace(c, '_');
        }

        // Also replace some that might cause issues
        safe = safe.Replace(":", "-")
                   .Replace("|", "-")
                   .Replace("*", "-")
                   .Replace("?", "")
                   .Replace("\"", "'");

        // Limit length
        if (safe.Length > 100)
        {
            safe = safe.Substring(0, 100);
        }

        return safe;
    }

    private static string EscapeYaml(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "");
    }
}
